apiVersion: v1
kind: Service
metadata:
  name: hippo-lb
  namespace: crunchy
spec:
  selector:
    postgres-operator.crunchydata.com/role: master
    postgres-operator.crunchydata.com/cluster: hippo
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
