apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
  namespace: keycloak
spec:
  selector:
    app.kubernetes.io/name: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
