apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: payments
spec:
  image: registry.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-5.2.0-0
  postgresVersion: 14
