apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:

  ###################################################################
  ##  Clone from Bridge
  ###################################################################
  dataSource:
    pgbackrest:
      configuration:
        - secret:
            name: pgo-azure-creds
      stanza: 47wuxjejivdl7gui6thjyk5j4i
      global:
        repo1-path: /
      repo:
        name: repo1
        azure:
          container: "47wuxjejivdl7gui6thjyk5j4i"

  ###################################################################
  ##  General Information about PostgreSQL
  ###################################################################
  #crunchy-postgres:ubi8-14.3-0
  #crunchy-postgres:ubi8-14.4-0
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.4-0
  openshift: true
  port: 5432
  postgresVersion: 14
  instances:
    - name: 'pgc'
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi

  ###################################################################
  ##  Backups
  ###################################################################
  backups:
    pgbackrest:
      image: registry.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-2
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          incremental: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 2Gi

  ###################################################################
  ##  Crunchy Collect Sidecar (Monitoring)
  ###################################################################
  monitoring:
    pgmonitor:
      exporter:
        image: registry.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.0-0

  ###################################################################
  ##  PostgreSQL Configuration
  ###################################################################
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_buffers: 256MB
          work_mem: 2MB
