apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  labels:
    app.kubernetes.io/name: postgrest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgrest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgrest
    spec:
      containers:
      - image: postgrest/postgrest
        name: postgrest
        resources: {}
        env:
        - name: PGRST_DB_SCHEMA
          value: "public"
        - name: PGRST_DB_URI
          valueFrom: { secretKeyRef: { name: pgnow-pguser-pgnow, key: uri } }
        - name: PGRST_DB_ANON_ROLE
          valueFrom: { secretKeyRef: { name: pgnow-pguser-pgnow, key: user } }
        - name: PGRST_OPENAPI_SERVER_PROXY_URI
          value: "http://127.0.0.1:3000"
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
      restartPolicy: Always
