apiVersion: v1
kind: Service
metadata:
  name: postgrest
spec:
  selector:
    app.kubernetes.io/name: postgrest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
